name: Coolapk Wiki CI

on:
    push:
        branches: master
    schedule:
        - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

        - uses: actions/checkout@v2

        - uses: actions/checkout@v2
          with:
              repository: Coolapk-Fan/wiki.wiki
              path: source/_posts

        - run: |
            curl https://cdn.jsdelivr.net/gh/Coolapk-Fan/wiki/README.md -o source/README.md
            mkdir source/tool/等级计算器 && curl https://cdn.jsdelivr.net/gh/Coolapk-Fan/wiki/tool/等级计算器/index.js -o source/tool/等级计算器/index.js
            mkdir source/tool/token && curl https://cdn.jsdelivr.net/gh/Coolapk-Fan/wiki/tool/token/index.html -o source/tool/token/index.html
            chmod +x title
            ./title
        - uses: actions/setup-node@v2-beta
          with:
              node-version: '12'
              check-latest: true
        
        - uses: actions/cache@v2
          id: cache
          with:
              path: node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: ${{ runner.os }}-node-
        
        - if: steps.cache.outputs.cache-hit != 'true'
          run: npm ci

        - uses: sma11black/hexo-action@v1.0.2
          with:
              deploy_key: ${{ secrets.DEPLOY_KEY }}
