name: Coolapk Wiki CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

        - uses: actions/checkout@v2
          with:
              submodules: true

        - uses: actions/setup-node@v2-beta
          with:
              node-version: '12'
              check-latest: true
        
        - uses: actions/cache@v2
          id: cache
          with:
              path: node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: ${{ runner.os }}-node-
        
        - if: steps.cache.outputs.cache-hit != 'true'
          run: npm ci

        - run: npm run build

        - uses: peaceiris/actions-gh-pages@v3
          with:
          personal_token: ${{ secrets.COOLAPK_TOKEN }}
          external_repository: Coolapk-Fan/wiki
          publish_dir: ./public
          publish_branch: master
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
