name: Coolapk Wiki CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

        - name: 安装依赖
          run: |
              sudo apt update
              sudo apt install -y nodejs git
        
        - name: 拉取源码
          run: |
              git clone https://github.com/LiHua-Official/coolapkwikitemp.git /opt/wiki
              cd /opt/wiki
              git clone https://github.com/Coolapk-Fan/wiki.wiki.git source/_posts
        
        - name: 更新 Node 模块
          run: |
              npm install hexo --save
              npm update
        
        - name: 设置SSH私钥
          env:
              DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          run: |
              mkdir ~/.ssh
              echo $DEPLOY_KEY > ~/.ssh/coolapkwiki
              chmod 600 ~/.ssh/coolapkwiki
              ssh-keyscan github.com >> ~/.ssh/known_hosts

        - name: 设置Git信息
          run: |
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        - name: 部署
          run: |
              hexo d --debug
        
        - name: 清理
          run: |
              rm -rf /opt/wiki/source/_posts
