name: Coolapk Wiki CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

        - name: 安装依赖
          run: |
              sudo apt update
              sudo apt install -y nodejs git
        
        - name: 拉取源码
          run: |
              git clone https://github.com/LiHua-Official/coolapkwikitemp.git /opt/wiki
              cd /opt/wiki
              git clone https://github.com/Coolapk-Fan/wiki.wiki.git source/_posts
        
        - name: 更新 Node 模块
          run: |
              npm update
        
        - name: 设置SSH私钥
          run: |
              mkdir $HOME/.ssh
              echo ${{ secrets.DEPLOY_KEY }} > $HOME/.ssh/coolapkwiki
              chmod 400 $HOME/.ssh/coolapkwiki
        
        - name: 部署
          run: |
              hexo d --debug
        
        - name: 清理
          run: |
              rm -rf /opt/wiki/source/_posts
